# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/cmake-3.12.4/bin/cmake

# The command to remove a file.
RM = /usr/local/cmake-3.12.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/travis/build/rj-ashatalov/otuscpp-hw-07

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/travis/build/rj-ashatalov/otuscpp-hw-07

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/cmake-3.12.4/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/cmake-3.12.4/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/cmake-3.12.4/bin/cpack --config ./CPackSourceConfig.cmake /home/travis/build/rj-ashatalov/otuscpp-hw-07/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/cmake-3.12.4/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/cmake-3.12.4/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/cmake-3.12.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/cmake-3.12.4/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/cmake-3.12.4/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/travis/build/rj-ashatalov/otuscpp-hw-07/CMakeFiles /home/travis/build/rj-ashatalov/otuscpp-hw-07/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/travis/build/rj-ashatalov/otuscpp-hw-07/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named patch_version

# Build rule for target.
patch_version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 patch_version
.PHONY : patch_version

# fast build rule for target.
patch_version/fast:
	$(MAKE) -f CMakeFiles/patch_version.dir/build.make CMakeFiles/patch_version.dir/build
.PHONY : patch_version/fast

#=============================================================================
# Target rules for targets named test_version

# Build rule for target.
test_version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_version
.PHONY : test_version

# fast build rule for target.
test_version/fast:
	$(MAKE) -f CMakeFiles/test_version.dir/build.make CMakeFiles/test_version.dir/build
.PHONY : test_version/fast

#=============================================================================
# Target rules for targets named bulk

# Build rule for target.
bulk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bulk
.PHONY : bulk

# fast build rule for target.
bulk/fast:
	$(MAKE) -f CMakeFiles/bulk.dir/build.make CMakeFiles/bulk.dir/build
.PHONY : bulk/fast

lib.o: lib.cpp.o

.PHONY : lib.o

# target to build an object file
lib.cpp.o:
	$(MAKE) -f CMakeFiles/patch_version.dir/build.make CMakeFiles/patch_version.dir/lib.cpp.o
.PHONY : lib.cpp.o

lib.i: lib.cpp.i

.PHONY : lib.i

# target to preprocess a source file
lib.cpp.i:
	$(MAKE) -f CMakeFiles/patch_version.dir/build.make CMakeFiles/patch_version.dir/lib.cpp.i
.PHONY : lib.cpp.i

lib.s: lib.cpp.s

.PHONY : lib.s

# target to generate assembly for a file
lib.cpp.s:
	$(MAKE) -f CMakeFiles/patch_version.dir/build.make CMakeFiles/patch_version.dir/lib.cpp.s
.PHONY : lib.cpp.s

src/InfinitSequence.o: src/InfinitSequence.cpp.o

.PHONY : src/InfinitSequence.o

# target to build an object file
src/InfinitSequence.cpp.o:
	$(MAKE) -f CMakeFiles/bulk.dir/build.make CMakeFiles/bulk.dir/src/InfinitSequence.cpp.o
.PHONY : src/InfinitSequence.cpp.o

src/InfinitSequence.i: src/InfinitSequence.cpp.i

.PHONY : src/InfinitSequence.i

# target to preprocess a source file
src/InfinitSequence.cpp.i:
	$(MAKE) -f CMakeFiles/bulk.dir/build.make CMakeFiles/bulk.dir/src/InfinitSequence.cpp.i
.PHONY : src/InfinitSequence.cpp.i

src/InfinitSequence.s: src/InfinitSequence.cpp.s

.PHONY : src/InfinitSequence.s

# target to generate assembly for a file
src/InfinitSequence.cpp.s:
	$(MAKE) -f CMakeFiles/bulk.dir/build.make CMakeFiles/bulk.dir/src/InfinitSequence.cpp.s
.PHONY : src/InfinitSequence.cpp.s

src/Sequence.o: src/Sequence.cpp.o

.PHONY : src/Sequence.o

# target to build an object file
src/Sequence.cpp.o:
	$(MAKE) -f CMakeFiles/bulk.dir/build.make CMakeFiles/bulk.dir/src/Sequence.cpp.o
.PHONY : src/Sequence.cpp.o

src/Sequence.i: src/Sequence.cpp.i

.PHONY : src/Sequence.i

# target to preprocess a source file
src/Sequence.cpp.i:
	$(MAKE) -f CMakeFiles/bulk.dir/build.make CMakeFiles/bulk.dir/src/Sequence.cpp.i
.PHONY : src/Sequence.cpp.i

src/Sequence.s: src/Sequence.cpp.s

.PHONY : src/Sequence.s

# target to generate assembly for a file
src/Sequence.cpp.s:
	$(MAKE) -f CMakeFiles/bulk.dir/build.make CMakeFiles/bulk.dir/src/Sequence.cpp.s
.PHONY : src/Sequence.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bulk.dir/build.make CMakeFiles/bulk.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bulk.dir/build.make CMakeFiles/bulk.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bulk.dir/build.make CMakeFiles/bulk.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/test_version.o: tests/test_version.cpp.o

.PHONY : tests/test_version.o

# target to build an object file
tests/test_version.cpp.o:
	$(MAKE) -f CMakeFiles/test_version.dir/build.make CMakeFiles/test_version.dir/tests/test_version.cpp.o
.PHONY : tests/test_version.cpp.o

tests/test_version.i: tests/test_version.cpp.i

.PHONY : tests/test_version.i

# target to preprocess a source file
tests/test_version.cpp.i:
	$(MAKE) -f CMakeFiles/test_version.dir/build.make CMakeFiles/test_version.dir/tests/test_version.cpp.i
.PHONY : tests/test_version.cpp.i

tests/test_version.s: tests/test_version.cpp.s

.PHONY : tests/test_version.s

# target to generate assembly for a file
tests/test_version.cpp.s:
	$(MAKE) -f CMakeFiles/test_version.dir/build.make CMakeFiles/test_version.dir/tests/test_version.cpp.s
.PHONY : tests/test_version.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... package"
	@echo "... test"
	@echo "... patch_version"
	@echo "... test_version"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... bulk"
	@echo "... install"
	@echo "... lib.o"
	@echo "... lib.i"
	@echo "... lib.s"
	@echo "... src/InfinitSequence.o"
	@echo "... src/InfinitSequence.i"
	@echo "... src/InfinitSequence.s"
	@echo "... src/Sequence.o"
	@echo "... src/Sequence.i"
	@echo "... src/Sequence.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/test_version.o"
	@echo "... tests/test_version.i"
	@echo "... tests/test_version.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

